# Generated by Django 2.1.2 on 2018-10-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0003_auto_20181025_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='type',
        ),
        migrations.AddField(
            model_name='musician',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
