# Generated by Django 2.1.2 on 2018-10-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0004_auto_20181025_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='gender',
            field=models.CharField(choices=[('m', 'man'), ('w', 'woman')], default='m', max_length=10),
        ),
    ]
