# Generated by Django 2.1.2 on 2018-10-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0005_musician_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='gender',
            field=models.CharField(choices=[('m', 'man'), ('w', 'woman')], default='m', help_text='性别', max_length=10),
        ),
    ]
