# Generated by Django 2.1.2 on 2018-10-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0006_auto_20181025_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
